apiVersion: v1
kind: Service
metadata:
  labels:
    app: downstream
  name: db
  namespace: vote
spec:
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
  selector:
    app: downstream
  
