apiVersion: v1
kind: Service
metadata:
  labels:
    app: downstream
  name: downstream
  namespace: vote
spec:
  type: NodePort
  ports:
  - name: "result-http"
    port: 5001
    targetPort: 80
    nodePort: 30881
  selector:
    app: downstream
