apiVersion: v1 
kind: Service 
metadata:
  labels:
    app: upstream
  name: upstream
  namespace: vote
spec:
  type: NodePort
  ports:
  - name: "vote-http"
    port: 5000
    targetPort: 80
    nodePort: 30880
  selector:
    app: upstream
  
