apiVersion: v1
kind: Service
metadata:
  labels:
    app: upstream
  name: redis
  namespace: vote
spec:
  ports:
  - name: "redis-service"
    port: 6379
    targetPort: 6379
  selector:
    app: upstream
  
